# SwiftLint Configuration for tracktides
# https://github.com/realm/SwiftLint

# Rules to enable that are not part of default set
opt_in_rules:
  - closure_spacing
  - explicit_init
  - fatal_error_message
  - force_unwrapping
  - implicitly_unwrapped_optional
  - overridden_super_call
  - redundant_nil_coalescing
  - sorted_imports
  - vertical_parameter_alignment_on_call
  - empty_count
  - multiline_parameters
  - closure_end_indentation
  - operator_usage_whitespace

# Rules to disable from default set
disabled_rules:
  - trailing_whitespace  # SwiftFormat handles this
  - explicit_type_interface  # Conflicts with SwiftFormat redundant type removal

# Analyzer rules (only run with 'swiftlint analyze')
analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import

# Paths to include
included:
  - tracktides

# Paths to exclude
excluded:
  - tracktides/Preview Content
  - .build
  - Pods
  - Carthage

# Rule-specific configuration
line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - url
    - URL
    - x
    - y
    - z

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50

# Force unwrapping should be avoided
force_unwrapping: error

# Implicitly unwrapped optionals should be avoided
implicitly_unwrapped_optional:
  mode: all_except_iboutlets
  severity: warning

# Custom rules
custom_rules:
  no_print:
    name: "No Print Statements"
    regex: '(print|debugPrint)\('
    match_kinds:
      - identifier
    message: "Use proper logging instead of print()"
    severity: warning
